### ISSUE TITLE
Package OnStove

### ISSUE THREAD

**Issue by babakkhavari** [Open-Source-Spatial-Clean-Cooking-Tool/OnStove#289]

**Comment by babakkhavari** [comment]
Rasterio requires gdal, which can not be installed using pip. Therefore pip does not work.

**Comment by babakkhavari** [comment]
After testing, the package creating problems for pip seems to be geopandas.

**Comment by babakkhavari** [comment]
**If we are to do it with Conda**

Type:

`conda build . -c bioconda -c jmcmurray -c conda-forge`

to create the package. 

Type: 

`conda install onstove -c bioconda -c jmcmurray -c conda-forge`

to install the package when created

**Comment by babakkhavari** [comment]
For anaconda I put together a meta.yaml:

`package:
  name: onstove
  version: "0.1.1"

source:
  git_url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove.git
  git_tag: bk/conda-package

requirements:
  host:
    - setuptools
    - python
  run:
    - python>=3.10
    - dill
    - geopandas>=0.11.1
    - matplotlib
    - plotnine>=0.9.0
    - psutil
    - psycopg2
    - python-decouple
    - rasterio>=1.3.2
    - scikit-image
    - svgpathtools
    - svgpath2mpl

test:
  imports:
    - onstove

about:
  home: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove/tree/bk/conda-package`

 a build.sh and a bld.bat

**Comment by babakkhavari** [comment]
Note that the packages in the `meta.yaml` match the packages in `environment.yml` (including the versions of different packages). The env yml can be installed following the README instructions, which I was hoping meant it would in the package as well.

**Comment by babakkhavari** [comment]
Changing the meta.yaml to:

```
package:
  name: onstove
  version: "0.1.1"

source:
  git_url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove.git
  git_tag: bk/conda-package

build: 
  noarch: python

requirements:
  host:
    - python>=3.10
  run:
    - python>=3.10
    - dill
    - geopandas>=0.11.1
    - matplotlib
    - plotnine>=0.9.0
    - psutil
    - psycopg2
    - python-decouple
    - rasterio>=1.3.2
    - scikit-image
    - svgpathtools
    - svgpath2mpl
test:
  imports:
    - onstove

about:
  home: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove/tree/bk/conda-package
```

and the setup.py to:

```
from setuptools import setup

setup(
    name='onstove',
    version='0.1.1',
    packages=['onstove'],
    python_requires='>=3.10',
    install_requires=['dill',
                      'geopandas >= 0.11.1',
                      'matplotlib',
                      'plotnine >= 0.9.0',
                      'psutil',
                      'psycopg2',
                      'python-decouple',
                      'rasterio >= 1.3.2',
                      'scikit-image',
                      'svgpathtools',
                      'svgpath2mpl']
)
```

Seems to be fixing the issue. Then a package can be created using: 
`
conda build . -c bioconda -c jmcmurray -c conda-forge
`
and installed by:

`conda install onstove -c PATH_TO_WHERE_bz_FILE_IS_STORED -c conda-forge`

I run into a memory error in JN though as soon as using a tool in the example,ipynb and kernel shuts down.

**Comment by babakkhavari** [comment]
This is a geopandas issue. Reading vector layers with OnStove and geopandas crash.

**Comment by babakkhavari** [comment]
So updating the meta.yaml to:

```
package:
  name: onstove
  version: "0.1.1"

source:
  git_url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove.git
  git_tag: bk/conda-package

build: 
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv

requirements:
  host:
    - python>=3.10
    - pip
  run:
    - python>=3.10
    - dill
    - geopandas
    - matplotlib
    - plotnine
    - psutil
    - jupyterlab
    - psycopg2
    - python-decouple
    - rasterio
    - scikit-image
    - svgpathtools
    - svgpath2mpl
test:
  imports:
    - onstove

about:
  home: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove/tree/bk/conda-package
```

and eptying out the build.sh and bld.bat seems to do the trick.

**Comment by camiloramirezgo** [comment]
We should publish to `conda-forge` to avoid dependencies conflicts and make it much easier to maintain the package updated. For that, we can use this recipe:
```
{% set name = "OnStove" %}
{% set version = "0.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/{{ name }}/archive/v{{ version }}.tar.gz
  sha256: 714b4b3f1bb3bdf02d5df3b64e89db8dffc72f3cf1c07484966026e55730ebc3

build: 
  noarch: python
  script: "{{ PYTHON }} -m pip install . -vv"

requirements:
  host:
    - python>=3.10
  run:
    - python>=3.10
    - dill
    - geopandas
    - matplotlib
    - plotnine
    - psutil
    - psycopg2
    - python-decouple
    - rasterio
    - scikit-image
    - svgpathtools
    - svgpath2mpl
test:
  imports:
    - onstove

about:
  home: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove
  summary: 'Python-based geospatial cost-benefit clean cooking tool, OnStove'
  description: |
    OnStove is a geospatial cost-benefit clean cooking tool that calculates 
    the net-benefits of different stove options in a given geography and compares 
    all stoves to one another with regards to their net-benefit.
  license: MIT
  license_family: MIT
  license_file: LICENSE
  doc_url: https://onstove-documentation.readthedocs.io/en/latest/?badge=latest
  dev_url: https://github.com/Open-Source-Spatial-Clean-Cooking-Tool/OnStove

extra:
  recipe-maintainers:
    - camiloramirezgo
    - babakkhavari
```
